// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5AIgkVrFj-x9b3g6rgXvsxN4C4vrOxaQ',
    appId: '1:948832859087:web:2647f658aadde046e798ba',
    messagingSenderId: '948832859087',
    projectId: 'savior-eedb3',
    authDomain: 'savior-eedb3.firebaseapp.com',
    storageBucket: 'savior-eedb3.appspot.com',
    measurementId: 'G-CW65RJB427',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCG3Vzms903_kMLQHmYoNeAnHzx2HFuSI',
    appId: '1:948832859087:android:89d0062afab8a7bae798ba',
    messagingSenderId: '948832859087',
    projectId: 'savior-eedb3',
    storageBucket: 'savior-eedb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnoNwbTeIG9fFtBAnUOonBsieBTeCod3s',
    appId: '1:948832859087:ios:1539db6d80343d15e798ba',
    messagingSenderId: '948832859087',
    projectId: 'savior-eedb3',
    storageBucket: 'savior-eedb3.appspot.com',
    iosClientId: '948832859087-ldla2qn4fks7lrf1rvkadasr3qtn1in2.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnoNwbTeIG9fFtBAnUOonBsieBTeCod3s',
    appId: '1:948832859087:ios:1539db6d80343d15e798ba',
    messagingSenderId: '948832859087',
    projectId: 'savior-eedb3',
    storageBucket: 'savior-eedb3.appspot.com',
    iosClientId: '948832859087-ldla2qn4fks7lrf1rvkadasr3qtn1in2.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );
}
